Repository lohhiiccc/Minishell, pull requests merged in 2024-04, with the labels that each got.

#66 rename t_env to t_param
  includes/build_in.h
  includes/env.h
  includes/exec.h
  includes/expand.h
  includes/expand_utils.h
  includes/heredoc.h
  includes/lexer.h
  includes/make_tree.h
  includes/minishell.h
  srcs/build-in/cd.c
  srcs/build-in/env.c
  srcs/build-in/exit.c
  srcs/build-in/unset.c
  srcs/exec/exec.c
  srcs/exec/exec_and.c
  srcs/exec/exec_apend.c
  srcs/exec/exec_build_in.c
  srcs/exec/exec_cmd.c
  srcs/exec/exec_exe.c
  srcs/exec/exec_here_doc.c
  srcs/exec/exec_input.c
  srcs/exec/exec_or.c
  srcs/exec/exec_output.c
  srcs/exec/exec_pipe.c
  srcs/exec/exec_utils.c
  srcs/expander/expand/expand_var.c
  srcs/expander/expand_cmd.c
  srcs/expander/expand_file.c
  srcs/expander/expand_wildcard.c
  srcs/expander/utils/expand_str.c
  srcs/expander/utils/have_wildecard.c
  srcs/here_doc/create_here_doc_file.c
  srcs/lexer/lexer.c
  srcs/lexer/print_syntax_error.c
  srcs/main.c
  srcs/parsing/make_tree/make_tree.c
  srcs/parsing/parsing.c
  srcs/prompt/prompt.c
Labels: norm

#67 Mjuffard
  includes/build_in.h
  lib/libft/includes/vector.h
  lib/libft/srcs/vector/ft_vector_iteri.c
  lib/libft/srcs/vector/ft_vector_iteri_fd.c
  lib/libft/srcs/vector/ft_vector_print_int.c
  lib/libft/srcs/vector/ft_vector_print_str.c
  lib/libft/srcs/vector/ft_vector_print_str_fd.c
  srcs/build-in/cd.c
  srcs/build-in/echo.c
  srcs/build-in/env.c
  srcs/build-in/exit.c
  srcs/build-in/export.c
  srcs/build-in/pwd.c
  srcs/env/init_env.c
  srcs/exec/exec_and.c
  srcs/exec/exec_cmd.c
  srcs/exec/exec_exe.c
  srcs/exec/exec_or.c
  srcs/exec/exec_utils.c
  srcs/expander/expand_file.c
  srcs/here_doc/here_doc_prompt.c
  srcs/here_doc/pars_heredoc.c
Labels: norm

#80 fix issue
  srcs/lexer/launch_checker.c
Labels: norm, crash, fix

#82 Mjuffard
  includes/build_in.h
  srcs/build-in/export.c
  srcs/exec/exec_build_in.c
Labels: fix

#88 fix memory leak whene nl was escape
  includes/minishell.h
  srcs/tools/token/get_next_token.c
Labels: fix
