Repository lohhiiccc/Minishell, pull requests merged in 2024-05, with the labels that each got.

#92 Norm mjuffard
  includes/env.h
  includes/lexer.h
  srcs/build-in/cd.c
  srcs/exec/exec_cmd.c
  srcs/exec/exec_exe.c
  srcs/exec/exec_input.c
  srcs/exec/exec_output.c
  srcs/exec/exec_pipe.c
Labels: norm

#89 fix norm
  includes/env.h
  includes/lexer.h
  srcs/build-in/cd.c
  srcs/exec/exec_cmd.c
  srcs/exec/exec_exe.c
  srcs/exec/exec_input.c
  srcs/exec/exec_output.c
  srcs/exec/exec_pipe.c
  srcs/expander/expand/expand_quote.c
  srcs/expander/expand_cmd.c
  srcs/expander/expand_file.c
  srcs/here_doc/here_doc_prompt.c
  srcs/lexer/launch_checker.c
  srcs/parsing/make_tree/make_tree.c
  srcs/prompt/prompt.c
Labels: norm

#91 fix wildcard not matching
  srcs/expander/wildcard/is_match.c
  srcs/expander/wildcard/wildcard.c
Labels: fix

#93 Fix tree
  srcs/parsing/make_tree/make_tree.c
  srcs/prompt/prompt.c
Labels: norm, fix

#96 fix unset and vector delete
  lib/libft/srcs/vector/ft_vector_delete_elem.c
  srcs/build-in/export.c
  srcs/build-in/unset.c
Labels: fix

#98 fix unset
  srcs/build-in/unset.c
Labels: fix

#99 Fix delete elem red
  srcs/exec/exec_apend.c
  srcs/exec/exec_here_doc.c
  srcs/exec/exec_input.c
  srcs/exec/exec_output.c
  srcs/prompt/prompt.c
Labels: crash

#101 Change Tacos with chicken
  includes/prompt.h
  srcs/here_doc/here_doc_prompt.c
Labels: Beauty

#103 fix unset again and no skin prompt if TERM has not a good value
  includes/prompt.h
  srcs/build-in/unset.c
  srcs/prompt/prompt.c
  srcs/prompt/prompt_skin.c
Labels: fix

#104 Norm
  lib/libft/srcs/mem/ft_free_tab.c
  lib/libft/srcs/put_fd/ft_putfloat_fd.c
  lib/libft/srcs/str/ft_split.c
  lib/libft/srcs/str/ft_strstrfjoin.c
  srcs/exec/exec_apend.c
  srcs/exec/exec_here_doc.c
  srcs/exec/exec_output.c
  srcs/exec/exec_pipe.c
  srcs/exec/exec_utils.c
  srcs/expander/expand_cmd.c
  srcs/expander/utils/add_var.c
  srcs/expander/wildcard/get_folder.c
  srcs/expander/wildcard/wildcard.c
  srcs/here_doc/create_here_doc_file.c
  srcs/here_doc/pars_heredoc.c
  srcs/lexer/lexer.c
  srcs/main.c
  srcs/parsing/make_tree/make_tree.c
  srcs/prompt/prompt.c
  srcs/tools/token/get_next_token.c
  srcs/tools/token/get_tokens.c
  srcs/tools/tree/ft_new_tree.c
  srcs/tools/tree/make_node/command.c
  srcs/tools/tree/make_node/redirection.c
Labels: norm

#105 fix bug
  srcs/here_doc/here_doc_prompt.c
Labels: fix

#106 Fix perm denied
  includes/prompt.h
  srcs/build-in/unset.c
  srcs/exec/exec_exe.c
Labels: fix

#107 Fix found path
  includes/prompt.h
  srcs/build-in/unset.c
  srcs/exec/exec_exe.c
  srcs/exec/find_path.c
Labels: fix

#110 fix segmentation fault and leak
  srcs/expander/expand_cmd.c
  srcs/expander/utils/add_var.c
Labels: fix

#112 norm
  includes/prompt.h
Labels: norm

#113 fix empty cmd
  srcs/exec/find_path.c
Labels: fix
